### ISSUE TITLE
Página LIS Vitrines

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#12]
Solicito a customização do https://bvsalud.org/lis-vitrinas com identificação de acordo com o  seu propósito que é fazer a gestão das páginas de vitrines produzidas pela rede.

Hoje há uma página provisória, criada pelo consultor. Na reunião para definição de vitrines em 2019 (documentação em https://paho.sharepoint.com/:f:/r/sites/BIR/TC/TC/Processos/Vitrines-do-Conhecimento?csf=1&web=1&e=ISiPtw ) ficou definido que seria customizado um LIS para substituir essa página. O LIS já existe, mas é necessário fazer a customização para que quando for acessado o usuário saiba que se trata de uma VITRINE. 

Sugiro os seguintes elementos:
Banner customizado para Vitrines do Conhecimento (3 idiomas)
Sobre /Sobre/ About (página WP com informação)
Inclua sua Vitrine do Conhecimento / Incluya su Vitrina del Conocimiento/ Include your Window of Knowledge (página WP com orientação)
Área de destaque para ultimas Vitrines (carrossel) 
Caixa de busca WP ( palavras do título e descritores de assunto )
Cluster para instância de BVS (será necessário fazer filtro por instância)
Clusters para descritor de assunto

**Comment by marcoslmori** [comment]
Criar um tema novo baseado no https://bvsalud.org/portal-lis/ de acordo com o solicitado na descrição desse ISSUE. 

A ideia é que seja mais genérico possível.

**Comment by pintoros** [comment]
De acordo com a reunião de 06/07/2021, segue a demanda para a nova página de Vitrines a ser desenvolvida em WP.

Banner  (4 idiomas)
Sobre /Sobre/ About (link para uma página com informação básica)
Área de destaque para ultimas Vitrines (carrossel)
Caixa de busca WP ( palavras do título e descritores de assunto )
Área de link para página Vitrines do Conhecimento na Rede BVS 
Área de link para vitrines de outras BVS

**Comment by marcoslmori** [comment]
Issue fechado e dando continuidade no issue:  https://github.com/bireme/lis-wp-plugin/issues/15
