### ISSUE TITLE
Instalar IM na vitrine do COVID-19 -  BVS Regional

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wp-vitrines#14]
Essa vitrine não tem:
https://bvsalud.org/vitrinas/post_vitrines/novo_coronavirus/

Mas nas vitrines antigas tem:
https://bvsalud.org/post_vitrines/genero-saude/

**Comment by renatomurasaki** [comment]
@wilsonmoura veja junto com o @marcoslmori para que qualquer subsite dentro da BVS Regional esteja corretamente configurado com o IM.

**Comment by marcoslmori** [comment]
ok

**Comment by marcoslmori** [comment]
Por favor, @wilsonmoura  mantém esse código  cc35e4af-7e84-4858-8607-473d81a1d7ba?

**Comment by wilsonmoura** [comment]
@marcoslmori pode usar o mesmo código, mas vale destacar que as perguntas que vão aparecer serão as mesmas que estão sendo exibidas no Portal. @renatomurasaki se o ideal é que as perguntas nesse site sejam diferentes, devemos criar no sistema IM um código dedicado e perguntas específicas para esse subsite.

**Comment by renatomurasaki** [comment]
@wilsonmoura ciente. @marcoslmori pode prosseguir.

**Comment by marcoslmori** [comment]
Chamado 8087 do ocomon em espera de atendimento

**Comment by marcoslmori** [comment]
@wilsonmoura  , o plugin foi ativado e configurado mas não aparece na coleção de vitrinas que é a página principal mas é um redirect da home.  Qual procedimento devo fazer?

Nessa versão tem o campo de link do survey. Qual é o link que se deve colocar nesse campo? 

Obrigado

**Comment by renatomurasaki** [comment]
@marcoslmori a coleção não é essa? - https://bvsalud.org/vitrinas/post_vitrines/
Para mim está mostrando.

Sobre o link do survey, não é necessário informar nada, pois este campo é usado quando se deseja oferecer para o usuário uma segunda etapa de perguntas e resposta utilizando um survey externo.

**Comment by renatomurasaki** [comment]
Nesta também aparece - https://bvsalud.org/post_vitrines/
