### ISSUE TITLE
Avaliar o tempo de carga do formulário

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#15]
![image](https://user-images.githubusercontent.com/10047460/127333335-33a14503-2084-49ad-8818-14474d0e15ac.png)

**Comment by marcoslmori** [comment]
Resumo da reunião:

O principal problema das vitrinas é a questão de performance em vários momentos.  No adicionar uma nova vitrina ou mesmo em editar o conteúdo mudando status dos componentes e gravando os dados. 

Cada componente tem em torno de 8 campos.  Analisando o código, o plugin trabalha campo por campo individualmente.  Grava um campo por vez com a função do Wordpress de campos customizados  e isso impacta  na gravação das informações.  Não trabalha em blocos. 

Para alterar o esquema de gravação para a gravação em blocos dos componentes e campos  impactará na estrutura dos dados que é guardada a informação e também na compatibilidade com os dados legados

Quanto ao carregamento deve ser analisado se a ordenação dos componentes pode estar impactando também na perfomance

Esse programa não utilizou nenhum plugin para ser desenvolvido

Quanto ao encaminhamentos
-  Os desenvolvedores irão analisar  o problema da performance do plugin
- Analisar qual tomada de decisão será feita levando dentro de um cenário  de fazer ajustes pontuais para melhorar o problema de performas nessa versão e fazer uma nova versão que não será compatível com o legado para que isso não seja um fator limitador para o desenvolvimento da nova versão do plugin

Será marcado uma nova reunião com a análise dos desenvolvedores para nova tomada de decisão

**Comment by viniciusandrade** [comment]
Nos testes locais com o plugin foram identificados os seguintes problemas inicias:
- warning ao ativar o plugin  “headers already sent”  --> esta mensagem indica que em algum ponto do plugin esta sendo enviado algum caracter para o output antes do header normal enviado pelo WP ... olhando os códigos identifiquei o problema no arquivo principal do plugin que possui saída HTML junto com código PHP
- log de erros do webserver: warning: Input variables exceeded 1000 --> foi necessário aumentar o valor do parâmetro max_input_vars para suprir esta mensagem
- aumento da memória dedicada aos scripts do WP --> definido no arquivo wp-config.php o parâmetro WP_MEMORY_LIMIT para 256M

Com estas alterações foi possível o uso local do plugin com tempo de resposta razoável. Ao se tentar estes mesmos ajustes no ambiente de teste o impacto na performance foi minimo uma vez que as instâncias possuem um conjunto grande de plugins ativos e a capaciade do servidor de testes é limitado.

**Comment by marcoslmori** [comment]
Nova instancia de vitrinas no servidor para testes

instancia:  https://vitrinas.teste.bireme.org/

Plugins instalados: 

- BVS Site
- Classic Editor
- Google Analytics for WordPress by MonsterInsights
- iThemes Security Pro
- Page Links To 
- Polylang 
- Vitrine do Conhecimento BVSalud

**Comment by viniciusandrade** [comment]
@marcoslmori realizei os seguintes ajustes para teste de otimização do plugin no novo ambiente:

Adicionado os seguintes parâmetros no .htaccess

php_value max_execution_time 200
php_value max_input_time 200
php_value max_input_vars 3000
php_value memory_limit 256M

Adicionado o seguinte parâmetros no wp-config.php

define( 'WP_MEMORY_LIMIT', '256M' );

Adicionado no plugin a seguinte linha para desabilitar o editor html para cada componente da vitrine:

add_filter( 'user_can_richedit' , create_function ( '$a' , 'return false;' ) , 50 );

Desmarquei "Opções de tela" a opção "Campos personalizados" 

Nos meus testes iniciais acredito que com estas alterações se torna viável o uso do plugin nos servidores de teste. Favor, quando possível avaliar.

**Comment by wilsonmoura** [comment]
@viniciusandrade conforme conversamos, fiz o refatoramento do código (#6) e descobri que a lentidão era devido ao carregamento de uma biblioteca de ícones via JavaScript.

@marcoslmori favor realizar a atualização do plugin e testar (já atualizei no ambiente criado para testar o plugin).

**Comment by renatomurasaki** [comment]
@wilsonmoura parabéns pelo achado!

**Comment by viniciusandrade** [comment]
@wilsonmoura show de bola!

**Comment by marcoslmori** [comment]
opa! Legal, vou instalar na Brasil e na vitrinas.bvsalud.!!

**Comment by marcoslmori** [comment]
copiado o arquivo plugin_vitrine.php da instancia https://wp-plugins.teste.bireme.org/vitrinas/ para as instancias https://brasil.teste.bvs.br/vitrinas/ e https://vitrinas.teste.bireme.org/

Fiz os teste básico e já ocorre a mensagem de "página sem resposta" e foi perceptível a melhora no carregamento dos campos do formulário

**Comment by marcoslmori** [comment]
reinstalado via git os plugins nas instancias acima

**Comment by wilsonmoura** [comment]
@marcoslmori conforme conversamos, basta apenas realizar o comando `git pull` para aplicar as correções, pois já estão todas versionadas em #6.

**Comment by marcoslmori** [comment]
Conforme conversado e para não causar duvidas, foi reinstalado via git clone

**Comment by marcoslmori** [comment]
Usuárias farão mais testes
