### ISSUE TITLE
Atualização plug-in Vitrines MTCI

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#19]
Solicito atualização do plugin de vitrines MTCI  https://mtci.bvsalud.org/vitrinas/wp-admin e se possível, verifica e habilitar a edição de conteúdo da unica vitrine publicada que não abre a edição nem via formulário, nem via widgets - https://mtci.bvsalud.org/vitrinas/wp-admin/post.php?post=1747&action=edit

**Comment by pintoros** [comment]
Oi Wilson, vi aqui uma atividade, mas não consegui identificar. Vc conseguiu ajustar?
Já posso acionar o ITI?
Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:692c3398-7f10-4cbb-8bfa-e6b26422006a]

________________________________
De: Wilson da Silva Moura ***@***.***>
Enviado: terça-feira, 20 de dezembro de 2022 03:57
Para: bireme/wp-vitrines ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/wp-vitrines] Atualização plug-in Vitrines MTCI (Issue #19)


Reopened #19<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwp-vitrines%2Fissues%2F19&data=05%7C01%7Cpintoros%40paho.org%7Ce21e7670b5464c98eedc08dae2576b13%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638071162355698570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sZ6LXHUHoxVAhgZhGVLUiPLymO13rKTwPrsd4AjF%2B98%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwp-vitrines%2Fissues%2F19%23event-8075550988&data=05%7C01%7Cpintoros%40paho.org%7Ce21e7670b5464c98eedc08dae2576b13%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638071162355698570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L3ukIHHOEtmfXwOINCcMrH2NGYRkGRrQTrd8VttYAB0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BIWKWWMDKGLUHLVXTWOFKENANCNFSM6AAAAAAS6PQ4RE&data=05%7C01%7Cpintoros%40paho.org%7Ce21e7670b5464c98eedc08dae2576b13%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638071162355854792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jRL4lx5UwSRP4LsC67QFvrHHZk95appQt0dr8K8GrDs%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by wilsonmoura** [comment]
@pintoros eu já acionei o ITI para atualizar o plugin no ambiente de produção (chamado OCOMON 8950).

**Comment by wilsonmoura** [comment]
@pintoros o plugin de vitrines no ambiente de produção foi atualizado. Favor validar.

**Comment by pintoros** [comment]
Abri outro chamado incluindo o @marcioalvessilva devido a desconfiguração das imagens após atualização do plug-in

**Comment by wilsonmoura** [comment]
@pintoros favor verificar atualização feita no issue #20 referente ao mesmo assunto.
