### ISSUE TITLE
Vitrine MTCI - desconfiguração de imagens

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#20]
O plug-in foi recentemente atualizad (#19) o, ao entrar na área de admin parece tudo OK, mas o tamanho das imagens foi desconfigurado e aparece uma linha vermelha ao redor dos títulos.

interface pública: https://mtci.bvsalud.org/vitrinas/pt/post_vitrines/contribuicoes-das-medicinas-tradicionais-complementares-e-integrativas-mtci-no-contexto-da-pandemia-da-covid-19/

Edição: https://mtci.bvsalud.org/vitrinas/wp-admin/post.php?post=1747&action=edit

**Comment by wilsonmoura** [comment]
@pintoros as imagens dessa vitrine, para serem exibidas corretamente, dependiam de um código CSS customizado que estava no editor padrão do WordPress. Ao verificar a área de edição notei que, por algum motivo, o editor padrão do WordPress foi desativado e, por conseguinte, ignorando o código CSS customizado que foi criado.

Vale reforçar que, ao desativar o editor padrão do WordPress, a área de Layout Simplificado fica disponível para uso e vice-versa. Na área de Layout Simplificado existe uma seção chamada Editor de CSS, que serve exatamente para inserir código CSS customizado em uma vitrine específica. Sendo assim, repliquei o mesmo código CSS que estava no editor padrão do WordPress nessa seção para normalizar a visualização das imagens. Favor validar.

**Comment by pintoros** [comment]
@wilsonmoura , o conteúdo dessa Vitrine está no Layout simplificado. Não aparece quando o editor padrão está ativado.
O ideal é configurar as imagens para serem exibidas corretamente no layout simplificado. Caso contrário não tenho como editar o conteúdo.
Se as imagens foram confirguradas com o editor padrão ativado vai sempre acontecer esse conflito.
A visualização está OK agora. 
Só preciso saber se posso continuar trabalhando no layout simplificado sem risco de desconfigurar .

**Comment by wilsonmoura** [comment]
@pintoros o problema foi que o código CSS customizado não estava no Layout Simplificado. Estava somente no editor padrão do WordPress. Para corrigir isso, conforme comentário anterior, eu repliquei o mesmo código CSS customizado na seção Editor de CSS que está disponível na área do Layout Simplificado. Sendo assim, pode continuar trabalhando nessa vitrine **sem impedimentos**.
