### ISSUE TITLE
Vitrine Yanomami

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#23]
Solicito aplicar harmonização de layout na Vitrine Yanomami, como expliquei, usei o formulário de Vitrines, o que limita alguns ajustes.
O conteúdo está colocado, fique a vontade para alterar cores, incluir ou alterar imagens e trabalhar com os links de resultados de busca no corpo da vitrine. A imagem central, usei da internet com CC.
Está disponível no WP : https://saudeindigena.bvs.br/vitrinas/wp-admin/
Publicada em: https://saudeindigena.bvs.br/vitrinas/post_vitrines/yanomami/

**Comment by marcioalvessilva** [comment]
Por favor validar!

![screencapture-saudeindigena-bvs-br-vitrinas-post-vitrines-yanomami-2023-02-08-10_22_53](https://user-images.githubusercontent.com/48724136/217564161-47494cde-7513-4bca-9426-f35c942fd722.jpg)

**Comment by pintoros** [comment]
@da Silva, Marcio ***@***.***> muito melhor!
Só uma sugestão, manter a paleta, porém clarear um pouco a ultima e a penúltima área de conteúdo. Achei que ficou um pouco escuro essas ultimas, mas gostei bastante dos tons e da letra branca também.
Sobre a parte inferior, em verde, o que acha de fechar um pouco mais esses tons para harmonizar com o verde mais forte do início, é uma sugestão, mas vc que é especialista decide rsrsrs



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d8dbbd0d-c421-4aa7-930a-52b30a6eeacb]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quarta-feira, 8 de fevereiro de 2023 11:51
Para: bireme/wp-vitrines ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/wp-vitrines] Vitrine Yanomami (Issue #23)


Por favor validar!

[screencapture-saudeindigena-bvs-br-vitrinas-post-vitrines-yanomami-2023-02-08-10_22_53]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F217564161-47494cde-7513-4bca-9426-f35c942fd722.jpg&data=05%7C01%7Cpintoros%40paho.org%7Ce7696cd252f94f1902d508db09e40129%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638114647130560375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JWahgLgAPOr9BLHhtPjRhCB1o1GDW%2FEl8xde6UdmB5I%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwp-vitrines%2Fissues%2F23%23issuecomment-1422718515&data=05%7C01%7Cpintoros%40paho.org%7Ce7696cd252f94f1902d508db09e40129%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638114647130560375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LfyMQ7YYPMDmxCV0AEgYGyeDIdmMS561uISRrtANy9A%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CN2UVQKCKFFHW343LWWOXIHANCNFSM6AAAAAAUNZXLN4&data=05%7C01%7Cpintoros%40paho.org%7Ce7696cd252f94f1902d508db09e40129%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638114647130560375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D0uVG2BHBHmAyfcFJvw%2BIMO34Hs2MMI1kb7zBeS2eIc%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Rose, acredito que você tenha alterado as cores, eu fiz uma correção nas cores e nos textos
![image](https://user-images.githubusercontent.com/48724136/219348687-abc97267-62ab-43f6-b8c2-cf019e6876e2.png)

**Comment by pintoros** [comment]
Alterei Márcio, pq achei clarinha. Obrigada por corrigir a cor dos textos.
Já pode fechar o essa solicitação.





Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e41c7e70-d8c6-4d2a-bbf0-12e2eab719f1]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 16 de fevereiro de 2023 08:11
Para: bireme/wp-vitrines ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/wp-vitrines] Vitrine Yanomami (Issue #23)


Rose, acredito que você tenha alterado as cores, eu fiz uma correção nas cores e nos textos
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F219348687-abc97267-62ab-43f6-b8c2-cf019e6876e2.png&data=05%7C01%7Cpintoros%40paho.org%7Ceb323eea4be04cc5fde808db100e84c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638121426774285073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UIv3kVQ4R2C6LJDP4xuqCiLHTfYTYYO4eIUw2ISTIlI%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwp-vitrines%2Fissues%2F23%23issuecomment-1432921489&data=05%7C01%7Cpintoros%40paho.org%7Ceb323eea4be04cc5fde808db100e84c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638121426774441270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vym71KZBR5p10Log9YwzWFVHJjy5QwIPUkeOfDULiQI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FDBP3NBJ2J7YQTHCLWXYDNFANCNFSM6AAAAAAUNZXLN4&data=05%7C01%7Cpintoros%40paho.org%7Ceb323eea4be04cc5fde808db100e84c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638121426774441270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PddDsngUdQy0RZMNWCQQK49ziDpRYqe0HP1AZEFksUE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
