### ISSUE TITLE
Vitrine Promoción de la Salud

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#24]
Solicito uma proposta de desenho para Vitrine disponível em ambiente de teste: 
https://vitrinas.teste.bvsalud.org/promocion-salud/es/post_vitrines/promocion-de-la-salud/ a ser apresentada na reunião do dia 14/02 (a confirmar)

Segue anexo documento guia para a customização solicitada pelo cliente e informação sobre o tipo de conteúdo a ser disponibilizado nessa vitrine.
[Design-Conteudo-Vitrina_Promocion-Salud.docx](https://github.com/bireme/wp-vitrines/files/10668295/Design-Conteudo-Vitrina_Promocion-Salud.docx)

**Comment by marcioalvessilva** [comment]
### **Versão 1**
![screencapture-vitrinas-teste-bvsalud-org-promocion-salud-es-post-vitrines-promocion-de-la-salud-2023-02-13-17_01_34](https://user-images.githubusercontent.com/48724136/218562618-54d41f87-6a91-42cc-876a-f54ffef98957.jpg)

### **Versão 2**
![screencapture-vitrinas-teste-bvsalud-org-promocion-salud-es-post-vitrines-promocion-de-la-salud-2023-02-13-17_01_48](https://user-images.githubusercontent.com/48724136/218562624-b0ad519c-4bdd-4d29-8162-c8f3e0410d5f.jpg)

**Comment by marcioalvessilva** [comment]
Proposta envida, em caso de novos ajustes por favor criar novo issue para alterações
Grato!
![image](https://user-images.githubusercontent.com/48724136/222764823-4775a88e-4177-4234-9098-274f94ff7ceb.png)
