### ISSUE TITLE
Vitrines SMS-SP - Resumo não aparece na página

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#25]
Solicito corrigir habilitar no plug-in da Vitrine SMS o resumo curto que aparece na página abaixo, como na Vitrine de COVID-19

https://sms.sp.bvs.br/vitrinas/post_vitrines

**Comment by marcoslmori** [comment]
chamado para o iti (9126)
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9126&id=x6Ar5QNk3t7W1r22JY2qdsTG43M%3D

**Comment by marcoslmori** [comment]
plugin atualizado e resumo curto agora disponível
