### ISSUE TITLE
Criar documentação com tags, classes, html css 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#26]
para ser aplicado nos plugins das vitrinas

**Comment by marcioalvessilva** [comment]
Segue documento de apoio para formatação das vitrines do conhecimento

[Documento de ajuda HTML e CSS para vitrines do conhecimento.docx](https://github.com/bireme/wp-vitrines/files/11222168/Documento.de.ajuda.HTML.e.CSS.para.vitrines.do.conhecimento.docx)

Por favor validar!

**Comment by marcioalvessilva** [comment]
Documento atualizado!

[Documento de ajuda HTML e CSS para vitrines do conhecimento.docx](https://github.com/bireme/wp-vitrines/files/11274038/Documento.de.ajuda.HTML.e.CSS.para.vitrines.do.conhecimento.docx)
