### ISSUE TITLE
Ajustes Plug-in 

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#27]
Inclusão de um elemento no Plug-in Vitrinas para permitir maior autonomia na construção, demandando menos do área de designer:

No layout simplificado:
1) Permitir a Inclusão de título na área e vídeos
![image](https://user-images.githubusercontent.com/29313904/230953157-dec1e462-0c2f-4534-907e-1d594355a428.png)

**Comment by wilsonmoura** [comment]
@pintoros ajustes realizados. Favor solicitar atualização do plugin no respectivo portal e validar.
