### ISSUE TITLE
Título do vídeo não aparece, mesmo cadastrado no formulário

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#29]
Formulário

![image](https://github.com/bireme/wp-vitrines/assets/10047460/9eff60a1-0991-483e-b401-9950c417f41a)

Apresentação

![image](https://github.com/bireme/wp-vitrines/assets/10047460/1a214958-4c19-4c1e-a1a2-950d3c12b49c)

**Comment by marcoslmori** [comment]
O "Voces para la equidade" que aparece no video, não é do formulário e sim do próprio video

Instancia testada foi em: https://vitrinas.bvsalud.org/grupos-situacion-vulnerabilidad/

Plugin atualizado em 05/07/2023

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor atualizar o plugin e validar.

**Comment by marcoslmori** [comment]
validado, está funcionando de acordo
