### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#30]
Solicito corrigir as linhas no footer e cor na barra de acessibilidade plug-in Vitrinas.
Obrigada

**Comment by marcioalvessilva** [comment]
Ola @pintoros !
Qual vitrine deve ser corrigida?

**Comment by pintoros** [comment]
Oi Márcio, se me lembro é uma correção no plug-in. Reflete nas vitrines publicadas:
https://vitrinas.bvsalud.org/grupos-situacion-vulnerabilidad/post_vitrines/grupos-en-situacion-de-vulnerabilidad/
https://vitrinas.bvsalud.org/promocion-salud/post_vitrines/promocion-de-la-salud/
Obrigada

**Comment by marcioalvessilva** [comment]
Ajustado!!
