### ISSUE TITLE
Vitrine Promoción de la Salud (continuaçao)

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#31]
Solicito a inclusão de mais duas áreas na Vitrina Promoción de la Salud ( https://vitrinas.bvsalud.org/promocion-salud/wp-admin/)
- Participación Social
- Salud en todas las Politicas
A sugestão para compor as imagens que vão ilustrar cada área está nos e-mails enviados (vc está em cópia) no dia 09 de outubro. 
Sugiro ajuste do conteúdo atual (coluna de países, por exemplo) para acomodar as duas novas áreas.

A partir da inclusão, vou fazer a tradução do conteúdo para Inglês, a pergunta é: 
Como trabalhar com o conteúdo que está em Tabs reponsive (https://vitrinas.bvsalud.org/promocion-salud/wp-admin/edit.php?post_type=tabs_responsive) é possível duplicar todo o conteúdo já existente somente para que eu traduza o nome dos países, (os links permanecerão os memos)?

**Comment by pintoros** [comment]
@marcioalvessilva 
Para não nos perder, ainda estão pendentes as propostas de imagens para 3 novas áreas da Vitrine:
**Atención Primaria a la Salud** - imagens sugeridas no e-mail da Margarita 16/out e 10/set
**Participación Social** -  imagens sugeridas no e-mail da Margarita 04/out
**Salud en todas las Politicas** -  imagens sugeridas no e-mail da Margarita 04/out
Vou reencaminhar todos pra você.

**Comment by marcioalvessilva** [comment]
Olá @pintoros , imagens enviadas por email.

![section4](https://github.com/bireme/wp-vitrines/assets/48724136/9b1d91e6-33c8-4420-a68f-92fedeab3ec5)
![section5](https://github.com/bireme/wp-vitrines/assets/48724136/e947f757-40a2-48c5-804d-e997f6e4cf8a)
![section6](https://github.com/bireme/wp-vitrines/assets/48724136/4cf658c0-956e-4ed8-b794-63396ecfe8d8)

**Comment by marcioalvessilva** [comment]
Finalizado!
