### ISSUE TITLE
Vitrina Promocón de la Salud - Ajuste da área de países

### ISSUE THREAD

**Issue by pintoros** [bireme/wp-vitrines#33]
Referente a reunião de 21/dez/23
Solicito fazer 2 desenhos para aprovação da área de países (para evitar tradução do conteúdo do Tabs Responsive):
1) Melhorar um pouco os espaços e talvez a letra dos títulos na proposta original (na teste)
2) A Pilar sugeriu tb fazer uma proposta com a lupa à frente dos textos, o que poderia amenizar os espaços em branco à frente dos títulos e também ganharíamos espaço entre as áreas
3) Usar um separador entre os títulos, colocando os títulos mais curtos na mesma linha: Entornos saludables, por exemplo
4) Traduzir as imagens da ultima área da vitrine para o português. Segue a tradução:
- Promoção da Saúde
-Campanhas Semana do Bem-Estar - https://www.paho.org/pt/campanhas/semana-do-bem-estar-2023
-Mais mulheres em bicicletas: uma política de transporte urbano a favor da saúde e da igualdade - https://www.paho.org/pt/historias/mais-mulheres-em-bicicletas-uma-politica-transporte-urbano-favor-da-saude-e-da-igualdade
- Governança urbana e participação comunitária na Cidade do México
- Construindo saúde com a comunidade

**Comment by marcioalvessilva** [comment]
![Campanhas-Semana-do-Bem-Estar-pt](https://github.com/bireme/wp-vitrines/assets/48724136/c21b9bc9-0437-4def-b65a-78d804160905)
![Promoção-da-Saúde-pt](https://github.com/bireme/wp-vitrines/assets/48724136/1cfee14d-f777-4944-a207-1542c48c281a)

![video2-pt](https://github.com/bireme/wp-vitrines/assets/48724136/d828ea2e-b845-4b0a-8028-29535bd7310a)
![video3-pt](https://github.com/bireme/wp-vitrines/assets/48724136/8e31880e-540d-41c8-a7b2-bfacea8fe6b4)
![video1-pt](https://github.com/bireme/wp-vitrines/assets/48724136/c18ad037-347d-4902-a600-6db20a01e971)

Uma pergunta, a imagem da semana do bem estar em português será diferente dos outros idomas

**Comment by marcioalvessilva** [comment]
Finalizado!
