### ISSUE TITLE
Deixar configurável os links de home e para página geral.

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#5]
Os links de home e da página geral estão todos no código do template do plugin.  Como o padrão atualmente é instalar em um wordpress baixo a instancia principal, o plugin não permite que seja configurado para onde o home deve apontar.

**Comment by wilsonmoura** [comment]
Observações:
- O link da home agora pode ser configurável em `Settings > WP-Vitrines`.
- O link da página geral não pode ser configurável, pois existe um padrão de URL para que ela funcione corretamente.
