### ISSUE TITLE
Avaliar a melhoria de performance  na lentidão no salvamento dos dados

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wp-vitrines#6]

**Comment by wilsonmoura** [comment]
Tarefa em fase de análise.

**Comment by marcoslmori** [comment]
Tem alguma data para ser analisado e implementado?.  O problema ocorre no âmbito das instancias (https://brasil.bvs.br/vitrinas/wp-admin/post.php?post=10&action=edit),  o portal regional tem um comportamento normal.
